linters:
  enable-all: true
  disable:
    - golint                    # Deprecated.
    - interfacer                # Deprecated.
    - maligned                  # Deprecated.
    - scopelint                 # Deprecated.
    - forbidigo                 # Fucking annoying.
    - godox                     # Fucking annoying.
    - gomnd                     # Fucking annoying.
    - gomoddirectives           # Fucking annoying.
    - varnamelen                # Fucking annoying.
    - wsl                       # Fuck you too!
