linters:
  enable-all: true
  disable:
    - golint                    # Deprecated.
    - interfacer                # Deprecated.
    - scopelint                 # Deprecated.
    - maligned                  # Deprecated.
    - gomnd                     # Fucking annoying.
    - godox                     # I'll have as much fucking TODOs as I want.
    - forbidigo                 # Fuck you too!
